@Suppress("unused")
object Versions {
    const val compileSdk = 32
    const val minSdk = 23
    const val targetSdk = 32

    const val appcompat = "1.5.0"
    const val base = "0.2.1"
    const val cameraXVersion = "1.1.0"
    const val constraintLayout = "2.1.4"
    const val coreKtx = "1.8.0"
    const val coreTesting = "2.1.0"
    const val coroutines = "1.6.4"
    const val datastore = "1.0.0"
    const val desugar = "1.1.5"
    const val espresso = "3.4.0"
    const val exoplayer = "2.18.1"
    const val firebase = "30.4.1"
    const val flexbox = "3.0.0"
    const val fragmentKtx = "1.5.2"
    const val glide = "4.13.2"
    const val googleTruth = "1.1.3"
    const val gradle = "4.2.1"
    const val guava = "31.1-android"
    const val hilt = "2.43.2"
    const val hiltWorker = "1.0.0"
    const val junit = "4.13.2"
    const val junitAndroid = "1.1.3"
    const val leakCanary = "2.9.1"
    const val legacy = "1.0.0"
    const val lifecycle = "2.5.1"
    const val lottie = "5.2.0"
    const val material = "1.6.1"
    const val navigation = "2.5.2"
    const val recyclerView = "1.2.1"
    const val retrofit = "2.9.0"
    const val robolectric = "4.7.3"
    const val room = "2.4.3"
    const val runner = "1.4.0"
    const val sdp = "1.1.0"
    const val ssp = "1.1.0"
    const val swipeRefreshLayout = "1.1.0"
    const val timber = "5.0.1"
    const val viewpager = "1.0.0"
    const val worker = "2.7.1"
}